### ISSUE TITLE
Waveguide.add_parameterized_path fails with multiple widths

### ISSUE THREAD

**Issue by fbeutel** [HelgeGehring/gdshelpers#27]
This seems to be a regression, because I think it worked before, but the following produces an error:

```
wg = Waveguide([0, 0], 0, [1, 2, 1])
wg.add_parameterized_path(lambda t: [10*t, 10*t])
wg.get_shapely_object()
```

Error:
```
Traceback (most recent call last):
  File "gdshelpers/tests/test_waveguide.py", line 40, in test_waveguide_multiple_widths
    wg.add_parameterized_path(some_path)
  File "gdshelpers/parts/waveguide.py", line 275, in add_parameterized_path
    poly_path_1 = sample_coordinates + start[..., None] * sample_coordinates_d1_normed_ortho
ValueError: operands could not be broadcast together with shapes (3,1) (28,2) 
```

I opened a pull request which adds a failing test case: #26

**Comment by HelgeGehring** [comment]
Thanks! I'd guess it should now be fixed in the pull request. I had to change slightly the path of the curve as it gave an additional error as the curvature seemed too high.
Could you have a look if it also runs fine with your other usages? Thanks!

**Comment by fbeutel** [comment]
Yes, seems to work now. Thanks for the fix!
